Anul 2/Sem2/Web Programming/L8-ASP/L8-ASP/Entities/Log.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace L8_ASP.Entities {
    public class Log {
        [Key]
        public int Id { get; set; }

        [Required]
        public string  Type { get; set; }

        [Required]
        public string Severity { get; set; }

        [Required]
        public DateTime Date { get; set; }

        [Required]
        public int UserId { get; set; } // Foreign Key to table User

        [Required]
        public string Description { get; set; }

        public Log() { }

        public Log(string type, string severity, DateTime date, int userId, string description) {
            this.Type = type;
            this.Severity = severity;
            this.Date = date;
            this.UserId = userId;
            this.Description = description;
        }
    }
}

Anul 2/Sem2/Web Programming/L8-ASP/L8-ASP/Entities/User.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace L8_ASP.Entities {
    public class User {
        [Key]
        public int Id { get; set; }

        [Required]
        [MinLength(4)]
        public string Username { get; set; }

        [Required]
        [MinLength(5)]
        public string Password { get; set; }

        public DateTime BirthDay { get; set; }

        public User() { }

        public User(string username, string password, DateTime birthday) {
            this.Username = username;
            this.Password = password;
            this.BirthDay = birthday;
        }
    }
}

Anul 2/Sem2/Web Programming/L8-ASP/L8-ASP/Models/ErrorViewModel.cs
namespace L8_ASP.Models {
    public class ErrorViewModel {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Anul 2/Sem2/Web Programming/L8-ASP/L8-ASP/Models/LogArrayViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using L8_ASP.Entities;

namespace L8_ASP.Models {
    public class LogArrayViewModel {
        public List<Log> Logs { get; set; }
    }
}

Anul 2/Sem2/Web Programming/L8-ASP/L8-ASP/Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using L8_ASP.Entities;
using L8_ASP.Models;
using L8_ASP.Services;

namespace L8_ASP.Controllers {
    public class AuthenticationController : Controller {
        private readonly AuthenticationService _authenticationService;
        public AuthenticationController(AuthenticationService authenticationService) {
            _authenticationService = authenticationService;
        }

        [HttpGet]
        public IActionResult Login() {
            return View();
        }

        [HttpPost]
        public IActionResult Login(User user) {
            
            var cookieData = _authenticationService.Authenticate(user.Username, user.Password);

            if (cookieData == null) {
                return View("Error", new ErrorViewModel());
            }

            Response.Cookies.Append(cookieData.Value.Key, cookieData.Value.Value, cookieData.Value.options);

            return Redirect("/Home/Index");
        }

        [HttpGet]
        public IActionResult Logout() {
            Response.Cookies.Delete("loginCookie");

            return Redirect("/");
        }

        [HttpGet]
        public IActionResult Register() {
            return View();
        }

        [HttpPost]
        public IActionResult Register(User user) {
            try {
                _authenticationService.Register(user.Username, user.Password, user.BirthDay);
            }
            catch (Exception) {
                return View("Error", new ErrorViewModel());
            }

            return Redirect("/Authentication/Login");
        }
    }
}

Anul 2/Sem2/Web Programming/L8-ASP/L8-ASP/Controllers/HomeController.cs
using L8_ASP.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace L8_ASP.Controllers {
    public class HomeController : Controller {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger) {
            _logger = logger;
        }

        public IActionResult Index() {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Anul 2/Sem2/Web Programming/L8-ASP/L8-ASP/Controllers/LogsController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using L8_ASP.Entities;
using L8_ASP.Models;
using L8_ASP.Services;

namespace L8_ASP.Controllers {
    public class LogsController : Controller {
        private readonly LogsService _logsService;

        public LogsController(LogsService logsService) {
            _logsService = logsService;
        }

        public IActionResult GetAll() {
            var model = new LogArrayViewModel {
                Logs = _logsService.GetAll().ToList()
            };

            return View(model);
        }

        public IActionResult GetAllForUser() {
            var userId = Int32.Parse(Request.Cookies.FirstOrDefault(c => c.Key == "loginCookie").Value);

            var model = new LogArrayViewModel {
                Logs = _logsService.GetAllForUser(userId).ToList()
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult AddLog() {
            return View();
        }

        [HttpPost]
        public IActionResult AddLog(Log log) {
            var userId = Int32.Parse(Request.Cookies.FirstOrDefault(c => c.Key == "loginCookie").Value);
            _logsService.AddLog(log.Type,log.Severity,log.Date, userId, log.Description);
            return Redirect("/Home/Index");
        }

        [HttpGet]
        public IActionResult DeleteLog() {
            return View();
        }

        [HttpPost]
        public IActionResult DeleteLog(int id) {
            var userId = Int32.Parse(Request.Cookies.FirstOrDefault(c => c.Key == "loginCookie").Value);

            try {
                _logsService.DeleteLog(userId, id);
            }
            catch (Exception) {
                return View("Error", new ErrorViewModel());
            }

            return Redirect("/Home/Index");
        }
    }
}

Anul 2/Sem2/Web Programming/L8-ASP/L8-ASP/Views/Authentication/Login.cshtml
@model L8_ASP.Entities.User

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Log In" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <div>
        <a asp-action="Register">Not registered? Sign in!</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Anul 2/Sem2/Web Programming/L8-ASP/L8-ASP/Views/Authentication/Register.cshtml
@model L8_ASP.Entities.User

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDay" class="control-label"></label>
                <input asp-for="BirthDay" class="form-control" />
                <span asp-validation-for="BirthDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <div>
        <a asp-controller="Authentication" asp-action="Login">Back to Log In</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Anul 2/Sem2/Web Programming/L8-ASP/L8-ASP/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>

    <div>
        <a asp-controller="Logs" asp-action="GetAll">Get All</a>
    </div>
    <div>
        <a asp-controller="Logs" asp-action="GetAllForUser">Get All for User</a>
    </div>
    <div>
        <a asp-controller="Logs" asp-action="AddLog">Add Log</a>
    </div>
    <div>
        <a asp-controller="Logs" asp-action="DeleteLog">Delete Log</a>
    </div>
</div>

Anul 2/Sem2/Web Programming/L8-ASP/L8-ASP/Views/Logs/AddLog.cshtml
@model L8_ASP.Entities.Log

<h4>Log</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddLog">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Severity" class="control-label"></label>
                <input asp-for="Severity" class="form-control" />
                <span asp-validation-for="Severity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index">Back to Home</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Anul 2/Sem2/Web Programming/L8-ASP/L8-ASP/Views/Logs/DeleteLog.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

<form asp-action="DeleteLog">
    <label>Id</label>
    <input type="number" name="id" class="form-control" />

    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

Anul 2/Sem2/Web Programming/L8-ASP/L8-ASP/Views/Logs/GetAll.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model LogArrayViewModel

<div>
    @foreach (var log in Model.Logs) {
        <div>
            <div>
                Type: @log.Type
            </div>
            <div>
                Severity: @log.Severity
            </div>
            <div>
                Date: @log.Date
            </div>
            <div>
                User ID: @log.UserId
            </div>
            <div>
                Description: @log.Description
            </div>
        </div>
        <br />
    }
</div>

Anul 2/Sem2/Web Programming/L8-ASP/L8-ASP/Views/Logs/GetAllForUser.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model LogArrayViewModel

<div>
    @foreach (var log in Model.Logs) {
        <div>
            <div>
                Type: @log.Type
            </div>
            <div>
                Severity: @log.Severity
            </div>
            <div>
                Date: @log.Date
            </div>
            <div>
                Description:
                <p>@log.Description</p>
            </div>
        </div>
        <br />
    }
</div>